# Generated by Django 2.2.12 on 2021-10-26 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('kort', models.CharField(max_length=80)),
                ('functie', models.TextField()),
                ('levensloop', models.TextField()),
            ],
            options={
                'verbose_name': 'entiteit',
                'verbose_name_plural': 'entiteiten',
            },
        ),
        migrations.CreateModel(
            name='Funcproc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('doel', models.CharField(max_length=80)),
                ('invoer', models.TextField()),
                ('uitvoer', models.TextField()),
                ('beschrijving', models.TextField()),
                ('bom', models.ManyToManyField(related_name='used_by', to='docs.Funcproc')),
            ],
            options={
                'verbose_name': 'functioneel proces',
                'verbose_name_plural': 'functionele processen',
            },
        ),
        migrations.CreateModel(
            name='Gebrtaak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('doel', models.CharField(max_length=80)),
                ('wanneer', models.TextField()),
                ('wie', models.TextField()),
                ('condities', models.TextField()),
                ('waarvoor', models.TextField()),
                ('beschrijving', models.TextField()),
            ],
            options={
                'verbose_name': 'gebruikerstaak',
                'verbose_name_plural': 'gebruikerstaken',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('kort', models.CharField(max_length=80)),
                ('oms', models.TextField()),
                ('start', models.CharField(max_length=80)),
                ('fysloc', models.CharField(max_length=80)),
                ('actiereg', models.CharField(max_length=40)),
                ('aruser', models.CharField(max_length=40)),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projecten',
            },
        ),
        migrations.CreateModel(
            name='Userwijz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('datum_in', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('gereed', models.BooleanField()),
                ('datum_gereed', models.DateTimeField(null=True)),
                ('wens', models.CharField(max_length=80)),
                ('toelichting', models.TextField()),
                ('opmerkingen', models.TextField()),
                ('actie', models.IntegerField(null=True)),
                ('actienummer', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfcs', to='docs.Project')),
            ],
            options={
                'verbose_name': 'aanvraag wijziging',
                'verbose_name_plural': 'aanvraag wijzigingen',
            },
        ),
        migrations.CreateModel(
            name='Userspec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('kort', models.CharField(max_length=80)),
                ('functie', models.TextField()),
                ('beeld', models.TextField()),
                ('product', models.TextField()),
                ('baten', models.CharField(max_length=80)),
                ('kosten', models.CharField(max_length=80)),
                ('opmerkingen', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='docs.Project')),
            ],
            options={
                'verbose_name': 'gebruikersspecificatie',
                'verbose_name_plural': 'gebruikersspecificaties',
            },
        ),
        migrations.CreateModel(
            name='Userprob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('datum_in', models.DateTimeField(auto_now_add=True)),
                ('gereed', models.BooleanField()),
                ('datum_gereed', models.DateTimeField(null=True)),
                ('kort', models.CharField(max_length=80)),
                ('melding', models.TextField()),
                ('oplossing', models.TextField()),
                ('actie', models.IntegerField(null=True)),
                ('actienummer', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probs', to='docs.Project')),
            ],
            options={
                'verbose_name': 'incident/probleem',
                'verbose_name_plural': 'incidenten/problemen',
            },
        ),
        migrations.CreateModel(
            name='Userdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('oms', models.CharField(max_length=80)),
                ('link', models.FileField(upload_to='userdocs')),
                ('tekst', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='docs.Project')),
            ],
            options={
                'verbose_name': 'naslagdocument',
                'verbose_name_plural': 'naslagdocumenten',
            },
        ),
        migrations.CreateModel(
            name='Testplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('oms', models.CharField(max_length=80)),
                ('tekst', models.TextField()),
                ('ent', models.ManyToManyField(related_name='tplan', to='docs.Entiteit')),
                ('fp', models.ManyToManyField(related_name='tplan', to='docs.Funcproc')),
                ('gt', models.ManyToManyField(related_name='tplan', to='docs.Gebrtaak')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tplan', to='docs.Project')),
            ],
            options={
                'verbose_name': 'testplan',
                'verbose_name_plural': 'testplannen',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('oms', models.CharField(max_length=80)),
                ('tekst', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcase', to='docs.Project')),
                ('tplan', models.ManyToManyField(related_name='tcase', to='docs.Testplan')),
            ],
            options={
                'verbose_name': 'testgeval',
                'verbose_name_plural': 'testgevallen',
            },
        ),
        migrations.CreateModel(
            name='Techtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('kort', models.CharField(max_length=80)),
                ('doel', models.TextField()),
                ('periode', models.TextField()),
                ('verloop', models.TextField()),
                ('gt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttask', to='docs.Gebrtaak')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttask', to='docs.Project')),
            ],
            options={
                'verbose_name': 'systeemtaak',
                'verbose_name_plural': 'systeemtaken',
            },
        ),
        migrations.CreateModel(
            name='Techproc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('doel', models.CharField(max_length=80)),
                ('invoer', models.TextField()),
                ('uitvoer', models.TextField()),
                ('beschrijving', models.TextField()),
                ('omgeving', models.TextField()),
                ('bom', models.ManyToManyField(related_name='used_by', to='docs.Techproc')),
                ('fp', models.ManyToManyField(related_name='tproc', to='docs.Funcproc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tproc', to='docs.Project')),
                ('tt', models.ManyToManyField(related_name='tproc', to='docs.Techtask')),
            ],
            options={
                'verbose_name': 'technisch proces',
                'verbose_name_plural': 'technische processen',
            },
        ),
        migrations.CreateModel(
            name='Procproc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('doel', models.CharField(max_length=80)),
                ('invoer', models.TextField()),
                ('uitvoer', models.TextField()),
                ('werkwijze', models.TextField()),
                ('bijzonder', models.TextField()),
                ('hoetetesten', models.TextField()),
                ('testgevallen', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pproc', to='docs.Project')),
                ('tp', models.ManyToManyField(related_name='pproc', to='docs.Techproc')),
            ],
            options={
                'verbose_name': 'programmabeschrijving',
                'verbose_name_plural': 'programmabeschrijvingen',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('kort', models.CharField(max_length=80)),
                ('data', models.TextField()),
                ('link', models.FileField(upload_to='layouts')),
                ('gt', models.ManyToManyField(related_name='layout', to='docs.Gebrtaak')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='docs.Project')),
                ('tp', models.ManyToManyField(related_name='layout', to='docs.Techproc')),
            ],
        ),
        migrations.AddField(
            model_name='gebrtaak',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gtaken', to='docs.Project'),
        ),
        migrations.AddField(
            model_name='gebrtaak',
            name='rfc',
            field=models.ManyToManyField(related_name='gtaken', to='docs.Userwijz'),
        ),
        migrations.AddField(
            model_name='gebrtaak',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtaken', to='docs.Userspec'),
        ),
        migrations.AddField(
            model_name='funcproc',
            name='gt',
            field=models.ManyToManyField(related_name='fprocs', to='docs.Gebrtaak'),
        ),
        migrations.AddField(
            model_name='funcproc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fprocs', to='docs.Project'),
        ),
        migrations.AddField(
            model_name='funcproc',
            name='rfc',
            field=models.ManyToManyField(related_name='fprocs', to='docs.Userwijz'),
        ),
        migrations.AddField(
            model_name='funcproc',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fprocs', to='docs.Userspec'),
        ),
        migrations.CreateModel(
            name='Funcdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('oms', models.CharField(max_length=80)),
                ('link', models.FileField(upload_to='funcdocs')),
                ('tekst', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdocs', to='docs.Project')),
            ],
            options={
                'verbose_name': 'functioneel document',
                'verbose_name_plural': 'functionele documenten',
            },
        ),
        migrations.AddField(
            model_name='entiteit',
            name='fp',
            field=models.ManyToManyField(related_name='fdata', to='docs.Funcproc'),
        ),
        migrations.AddField(
            model_name='entiteit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdata', to='docs.Project'),
        ),
        migrations.AddField(
            model_name='entiteit',
            name='rfc',
            field=models.ManyToManyField(related_name='fdata', to='docs.Userwijz'),
        ),
        migrations.CreateModel(
            name='Dataitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('functie', models.CharField(max_length=80)),
                ('levensloop', models.TextField()),
                ('ent', models.ManyToManyField(related_name='tdata', to='docs.Entiteit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdata', to='docs.Project')),
                ('tp', models.ManyToManyField(related_name='tdata', to='docs.Techproc')),
            ],
            options={
                'verbose_name': 'data-item',
                'verbose_name_plural': 'data-items',
            },
        ),
        migrations.CreateModel(
            name='Dataelement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('omschrijving', models.CharField(max_length=80)),
                ('soort', models.CharField(max_length=40)),
                ('sleutel', models.PositiveSmallIntegerField(verbose_name='volgorde in sleutel')),
                ('hoort_bij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elems', to='docs.Dataitem')),
                ('relatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatie', to='docs.Dataitem')),
            ],
            options={
                'verbose_name': 'data-element',
                'verbose_name_plural': 'data-elementen',
            },
        ),
        migrations.CreateModel(
            name='Bevinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('datum_in', models.DateTimeField(auto_now_add=True)),
                ('gereed', models.BooleanField()),
                ('datum_gereed', models.DateTimeField(null=True)),
                ('kort', models.CharField(max_length=80)),
                ('melding', models.TextField()),
                ('oplossing', models.TextField()),
                ('actie', models.IntegerField(null=True)),
                ('actienummer', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbev', to='docs.Project')),
                ('tplan', models.ManyToManyField(related_name='tbev', to='docs.Testplan')),
            ],
            options={
                'verbose_name': 'bevinding',
                'verbose_name_plural': 'bevindingen',
            },
        ),
        migrations.CreateModel(
            name='Attribuut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('A', 'Tekst'), ('N', 'Numeriek (geheel getal)'), ('B', 'Bedrag (numeriek, cijfers achter de komma)'), ('D', 'Datum')], max_length=10)),
                ('bereik', models.TextField()),
                ('primarykey', models.PositiveSmallIntegerField()),
                ('hoort_bij', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='docs.Entiteit')),
                ('relatie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatie', to='docs.Entiteit')),
            ],
            options={
                'verbose_name': 'attribuut',
                'verbose_name_plural': 'attributen',
            },
        ),
    ]
