# Generated by Django 5.1.7 on 2025-04-01 10:08

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wwwloc',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.functions.text.Concat(models.Value('http://cgit.lemoncurry.nl/'), django.db.models.functions.text.Right('fysloc', django.db.models.expressions.CombinedExpression(django.db.models.functions.text.StrIndex(django.db.models.functions.text.Reverse('fysloc'), models.Value('/')), '-', models.Value(1))), models.Value('/.git')), output_field=models.CharField(max_length=80)),
        ),
    ]
